// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Models;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210171141_AddTeacherSubjects")]
    partial class AddTeacherSubjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MyMvcApp.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Class 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Class 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Class 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Class 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Class 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Class 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Class 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Class 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Class 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Class 10"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.EnrollmentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId");

                    b.ToTable("EnrollmentHistories");
                });

            modelBuilder.Entity("MyMvcApp.Models.ParentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FatherName")
                        .HasColumnType("longtext");

                    b.Property<string>("FatherPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("MotherName")
                        .HasColumnType("longtext");

                    b.Property<string>("MotherPhone")
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("MyMvcApp.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClassroomId = 1,
                            Name = "A"
                        },
                        new
                        {
                            Id = 2,
                            ClassroomId = 1,
                            Name = "B"
                        },
                        new
                        {
                            Id = 3,
                            ClassroomId = 1,
                            Name = "C"
                        },
                        new
                        {
                            Id = 4,
                            ClassroomId = 1,
                            Name = "D"
                        },
                        new
                        {
                            Id = 5,
                            ClassroomId = 2,
                            Name = "A"
                        },
                        new
                        {
                            Id = 6,
                            ClassroomId = 2,
                            Name = "B"
                        },
                        new
                        {
                            Id = 7,
                            ClassroomId = 2,
                            Name = "C"
                        },
                        new
                        {
                            Id = 8,
                            ClassroomId = 2,
                            Name = "D"
                        },
                        new
                        {
                            Id = 9,
                            ClassroomId = 3,
                            Name = "A"
                        },
                        new
                        {
                            Id = 10,
                            ClassroomId = 3,
                            Name = "B"
                        },
                        new
                        {
                            Id = 11,
                            ClassroomId = 3,
                            Name = "C"
                        },
                        new
                        {
                            Id = 12,
                            ClassroomId = 3,
                            Name = "D"
                        },
                        new
                        {
                            Id = 13,
                            ClassroomId = 4,
                            Name = "A"
                        },
                        new
                        {
                            Id = 14,
                            ClassroomId = 4,
                            Name = "B"
                        },
                        new
                        {
                            Id = 15,
                            ClassroomId = 4,
                            Name = "C"
                        },
                        new
                        {
                            Id = 16,
                            ClassroomId = 4,
                            Name = "D"
                        },
                        new
                        {
                            Id = 17,
                            ClassroomId = 5,
                            Name = "A"
                        },
                        new
                        {
                            Id = 18,
                            ClassroomId = 5,
                            Name = "B"
                        },
                        new
                        {
                            Id = 19,
                            ClassroomId = 5,
                            Name = "C"
                        },
                        new
                        {
                            Id = 20,
                            ClassroomId = 5,
                            Name = "D"
                        },
                        new
                        {
                            Id = 21,
                            ClassroomId = 6,
                            Name = "A"
                        },
                        new
                        {
                            Id = 22,
                            ClassroomId = 6,
                            Name = "B"
                        },
                        new
                        {
                            Id = 23,
                            ClassroomId = 6,
                            Name = "C"
                        },
                        new
                        {
                            Id = 24,
                            ClassroomId = 6,
                            Name = "D"
                        },
                        new
                        {
                            Id = 25,
                            ClassroomId = 7,
                            Name = "A"
                        },
                        new
                        {
                            Id = 26,
                            ClassroomId = 7,
                            Name = "B"
                        },
                        new
                        {
                            Id = 27,
                            ClassroomId = 7,
                            Name = "C"
                        },
                        new
                        {
                            Id = 28,
                            ClassroomId = 7,
                            Name = "D"
                        },
                        new
                        {
                            Id = 29,
                            ClassroomId = 8,
                            Name = "A"
                        },
                        new
                        {
                            Id = 30,
                            ClassroomId = 8,
                            Name = "B"
                        },
                        new
                        {
                            Id = 31,
                            ClassroomId = 8,
                            Name = "C"
                        },
                        new
                        {
                            Id = 32,
                            ClassroomId = 8,
                            Name = "D"
                        },
                        new
                        {
                            Id = 33,
                            ClassroomId = 9,
                            Name = "A"
                        },
                        new
                        {
                            Id = 34,
                            ClassroomId = 9,
                            Name = "B"
                        },
                        new
                        {
                            Id = 35,
                            ClassroomId = 9,
                            Name = "C"
                        },
                        new
                        {
                            Id = 36,
                            ClassroomId = 9,
                            Name = "D"
                        },
                        new
                        {
                            Id = 37,
                            ClassroomId = 10,
                            Name = "A"
                        },
                        new
                        {
                            Id = 38,
                            ClassroomId = 10,
                            Name = "B"
                        },
                        new
                        {
                            Id = 39,
                            ClassroomId = 10,
                            Name = "C"
                        },
                        new
                        {
                            Id = 40,
                            ClassroomId = 10,
                            Name = "D"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Roll")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("SectionId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("MyMvcApp.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bangla"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Social Studies"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClassAssignedId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClassAssignedId");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<bool>("Present")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherAttendances");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherLeave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherLeaves");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SalaryMonth")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSalaries");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("MyMvcApp.Models.EnrollmentHistory", b =>
                {
                    b.HasOne("MyMvcApp.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.Student", "Student")
                        .WithMany("EnrollmentHistories")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyMvcApp.Models.ParentInfo", b =>
                {
                    b.HasOne("MyMvcApp.Models.Student", "Student")
                        .WithOne("ParentInfo")
                        .HasForeignKey("MyMvcApp.Models.ParentInfo", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MyMvcApp.Models.Section", b =>
                {
                    b.HasOne("MyMvcApp.Models.Classroom", "Classroom")
                        .WithMany("Sections")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("MyMvcApp.Models.Student", b =>
                {
                    b.HasOne("MyMvcApp.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId");

                    b.HasOne("MyMvcApp.Models.Section", "Section")
                        .WithMany("Students")
                        .HasForeignKey("SectionId");

                    b.Navigation("Classroom");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("MyMvcApp.Models.Teacher", b =>
                {
                    b.HasOne("MyMvcApp.Models.Classroom", "ClassAssigned")
                        .WithMany()
                        .HasForeignKey("ClassAssignedId");

                    b.Navigation("ClassAssigned");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherAttendance", b =>
                {
                    b.HasOne("MyMvcApp.Models.Teacher", "Teacher")
                        .WithMany("Attendances")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherLeave", b =>
                {
                    b.HasOne("MyMvcApp.Models.Teacher", "Teacher")
                        .WithMany("Leaves")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherSalary", b =>
                {
                    b.HasOne("MyMvcApp.Models.Teacher", "Teacher")
                        .WithMany("Salaries")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyMvcApp.Models.TeacherSubject", b =>
                {
                    b.HasOne("MyMvcApp.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("MyMvcApp.Models.Classroom", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("MyMvcApp.Models.Section", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("MyMvcApp.Models.Student", b =>
                {
                    b.Navigation("EnrollmentHistories");

                    b.Navigation("ParentInfo");
                });

            modelBuilder.Entity("MyMvcApp.Models.Teacher", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Leaves");

                    b.Navigation("Salaries");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
